# Helm values configuration for MyFamily Gazette Service
# Version: 1.0.0
# Dependencies:
# - kubernetes: 1.24+
# - helm: 3.8+

# Number of replicas for high availability
replicaCount: 3

# Container image configuration
image:
  repository: myfamily/gazette-service
  tag: latest
  pullPolicy: IfNotPresent

# Service naming
nameOverride: "gazette-service"
fullnameOverride: "myfamily-gazette-service"

# Service account configuration
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/gazette-service-role
  name: "gazette-service-account"

# Pod annotations for monitoring and security
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"
  prometheus.io/path: "/metrics"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "gazette-service"

# Pod security context
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Container security context
securityContext:
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false

# Service configuration
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  protocol: TCP

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
  hosts:
    - host: gazette-api.myfamily.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gazette-tls
      hosts:
        - gazette-api.myfamily.com

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Horizontal Pod Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30

# Node selection and affinity
nodeSelector:
  kubernetes.io/os: linux
  node-type: application

# Pod tolerations
tolerations:
  - key: "application"
    operator: "Equal"
    value: "gazette"
    effect: "NoSchedule"

# Pod and node affinity rules
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - gazette-service
          topologyKey: kubernetes.io/hostname
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-type
              operator: In
              values:
                - application

# Environment variables
env:
  PRINT_SERVICE_API_URL: "https://print-api.myfamily.com"
  PRINT_SERVICE_API_KEY: "${PRINT_SERVICE_API_KEY}"
  SHIPPING_SERVICE_ENDPOINT: "https://shipping-api.myfamily.com"
  SHIPPING_SERVICE_API_KEY: "${SHIPPING_SERVICE_API_KEY}"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  MAX_CONCURRENT_JOBS: "5"
  JOB_TIMEOUT_SECONDS: "300"

# ConfigMap for service configuration
configMap:
  name: gazette-config
  data:
    print.json:
      defaultFormat: "A4"
      resolution: 300
      colorSpace: "CMYK"
      bleed: 3
      binding: "PERFECT"
      paperStock:
        cover: 250
        interior: 150
    shipping.json:
      timeout: 30000
      retries: 3
      regions:
        - "Israel"
        - "Europe"
        - "North America"
        - "Australia"
      priorityLevels:
        standard: "5-7 days"
        express: "2-3 days"

# Secrets configuration
secrets:
  name: gazette-secrets
  type: Opaque

# Health check probes
livenessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 30
  successThreshold: 1